### ISSUE TITLE
Advanced

### ISSUE THREAD

**Issue by galalhassan** [csdeptku/CS126-Python#1]
check_numeric.py:
To make the code perfect, we still need to deal with the situation of having spaces in the middle.
Python is ready for that and provide us with the method strip, which removes all spaces at the beginning and at the end of the string (but not in the middle). We can use it instead of removing all spaces in the input string.
Example: " 23  34  ".strip( ) will return: "23 34".
So we can know that this string is not of integer format (because of the space in the middle).

**Comment by halmohri** [comment]
That's a good point. I updated the code.
